<?php

$nama			= strtoupper($_GET["term"]);

$db 			= getDB("storage");
	
/*$query 			= "select ID, NAMA from MASTER_PBM WHERE NAMA LIKE '%$nama%' "; */

$query 			= "SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'RECEIVING' KEGIATAN FROM nota_receiving WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'STUFFING' KEGIATAN FROM nota_stuffing WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
UNION 
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL,  'STRIPPING' KEGIATAN  FROM nota_stripping WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL,  'DELIVERY' KEGIATAN  FROM nota_delivery WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL,  'RELOKASI' KEGIATAN  FROM nota_relokasi WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'BATALMUAT' KEGIATAN FROM nota_batal_muat WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
UNION
SELECT NO_NOTA,NO_FAKTUR, NO_REQUEST, EMKL, 'RELOKASI_MTY' KEGIATAN FROM nota_relokasi_mty WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'PNKN_DELIVERY' KEGIATAN FROM nota_pnkn_del WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'PNKN_STUFFING' KEGIATAN FROM nota_pnkn_stuf WHERE (NO_NOTA LIKE '%$nama%' OR NO_FAKTUR LIKE '%$nama%')
AND STATUS <> 'BATAL'
";

//$query = "SELECT TRX_NUMBER NO_NOTA, TRX_NUMBER NO_FAKTUR, NO_REQUEST FROM NOTA_ALL_H" 

$result			= $db->query($query);
$row			= $result->getAll();	
//echo $query;
echo json_encode($row);


?>