<?php
$no_cont		= strtoupper($_GET["term"]);
$id_yard		= $_SESSION["IDYARD_STORAGE"];

$db 			= getDB("storage");
	
/*$query 			= "
				   SELECT MASTER_CONTAINER.NO_CONTAINER, 
                          MASTER_CONTAINER.SIZE_ AS SIZE_, 
                          MASTER_CONTAINER.TYPE_ AS TYPE_,
                          BP_CON.CONFIRM_DATE AS TGL_BONGKAR,
                          PKK.VOYAGE_IN AS VOYAGE
                   FROM USTER.MASTER_CONTAINER  MASTER_CONTAINER
                   INNER JOIN PETIKEMAS_CABANG.TTD_BP_CONFIRM BP_CON ON MASTER_CONTAINER.NO_CONTAINER = BP_CON.CONT_NO_BP
                   INNER JOIN PETIKEMAS_CABANG.PKK PKK ON BP_CON.NO_UKK = PKK.NO_UKK
                   WHERE MASTER_CONTAINER.NO_CONTAINER LIKE '%$no_cont%' AND MASTER_CONTAINER.LOCATION NOT LIKE 'GATOk' AND MASTER_CONTAINER.NO_CONTAINER NOT IN (SELECT NO_CONTAINER FROM USTER.CONTAINER_DELIVERY WHERE AKTIF = 'Y') AND MASTER_CONTAINER.NO_CONTAINER NOT IN (SELECT NO_CONTAINER FROM USTER.CONTAINER_STRIPPING WHERE AKTIF = 'Y')";
*/

$query	= "SELECT MASTER_CONTAINER.NO_CONTAINER AS NO_CONTAINER, 
                          MASTER_CONTAINER.SIZE_ AS SIZE_, 
                          MASTER_CONTAINER.TYPE_ AS TYPE_,
                          MAX(BP_CON.CONFIRM_DATE) AS TGL_BONGKAR,
                          YARD_AREA.ID AS ID_YARD, 
                          YARD_AREA.NAMA_YARD AS NAMA_YARD
                   FROM USTER.MASTER_CONTAINER  MASTER_CONTAINER
                   INNER JOIN PETIKEMAS_CABANG.TTD_BP_CONFIRM BP_CON ON MASTER_CONTAINER.NO_CONTAINER = BP_CON.CONT_NO_BP
                   JOIN PLACEMENT ON MASTER_CONTAINER.NO_CONTAINER = PLACEMENT.NO_CONTAINER
                   JOIN BLOCKING_AREA ON BLOCKING_AREA.ID = PLACEMENT.ID_BLOCKING_AREA
                   JOIN YARD_AREA ON YARD_AREA.ID = BLOCKING_AREA.ID_YARD_AREA
                   WHERE  MASTER_CONTAINER.NO_CONTAINER LIKE '%$no_cont%' AND MASTER_CONTAINER.LOCATION NOT LIKE 'GATOa' AND MASTER_CONTAINER.NO_CONTAINER NOT IN (SELECT NO_CONTAINER FROM USTER.CONTAINER_DELIVERY WHERE AKTIF = 'Y') AND MASTER_CONTAINER.NO_CONTAINER NOT IN (SELECT NO_CONTAINER FROM USTER.CONTAINER_STRIPPING WHERE AKTIF = 'Y')
                   GROUP BY MASTER_CONTAINER.NO_CONTAINER, SIZE_, TYPE_, YARD_AREA.ID, YARD_AREA.NAMA_YARD
                
				   ";

$result			= $db->query($query);
$row			= $result->getAll();	

//debug($result);
//print_r($row);
//echo $query;
echo json_encode($row);


?>