<?php
$no_cont		= strtoupper($_GET["term"]);

$db 			= getDB("storage");


$query	=" SELECT MASTER_CONTAINER.NO_CONTAINER, 
                          NVL(PLAN_CONTAINER_STUFFING.ASAL_CONT,'DEPO') ASAL_CONT,
                          CONTAINER_STUFFING.NO_REQUEST AS NO_REQ_STUFF,
                          CONTAINER_STUFFING.TYPE_STUFFING AS VIA,
                          CONTAINER_STUFFING.COMMODITY AS KOMODITI,
                          CONTAINER_STUFFING.HZ AS HZ,
                          MASTER_CONTAINER.SIZE_ AS SIZE_, 
                          MASTER_CONTAINER.TYPE_ AS TYPE_,
                          REQUEST_STUFFING.TGL_REQUEST AS TGL_REQUEST,
						  REQUEST_STUFFING.STUFFING_DARI AS STUFFING_DARI,
                          CONTAINER_STUFFING.NO_SEAL AS NO_SEAL,
                          CONTAINER_STUFFING.BERAT AS BERAT,
                          CONTAINER_STUFFING.KETERANGAN AS KETERANGAN                        
                   FROM MASTER_CONTAINER 
                   INNER JOIN CONTAINER_STUFFING 
                        ON MASTER_CONTAINER.NO_CONTAINER = CONTAINER_STUFFING.NO_CONTAINER
                   JOIN REQUEST_STUFFING 
                        ON CONTAINER_STUFFING.NO_REQUEST = REQUEST_STUFFING.NO_REQUEST
                    LEFT JOIN PLAN_CONTAINER_STUFFING ON PLAN_CONTAINER_STUFFING.NO_CONTAINER = CONTAINER_STUFFING.NO_CONTAINER 
                        AND CONTAINER_STUFFING.NO_REQUEST = REPLACE(PLAN_CONTAINER_STUFFING.NO_REQUEST,'P','S')
                   LEFT JOIN NOTA_STUFFING ON REQUEST_STUFFING.NO_REQUEST = NOTA_STUFFING.NO_REQUEST
                   JOIN KAPAL_CABANG.MST_PBM EMKL
                        ON REQUEST_STUFFING.KD_CONSIGNEE = emkl.KD_PBM AND emkl.KD_CABANG = '05'
                   WHERE MASTER_CONTAINER.NO_CONTAINER LIKE '%$no_cont%'   
                   AND CONTAINER_STUFFING.AKTIF = 'Y'";
	
/*	
$query 			= "SELECT MASTER_CONTAINER.NO_CONTAINER, 
                          MASTER_CONTAINER.SIZE_ AS SIZE_, 
                          MASTER_CONTAINER.TYPE_ AS TYPE_,
						  CONTAINER_STUFFING.COMMODITY AS COMMODITY,
						  CONTAINER_STUFFING.HZ AS HZ,
						  CONTAINER_STUFFING.NO_REQUEST AS NO_REQUEST,
						  CONTAINER_STUFFING.TYPE_STUFFING AS TYPE,
						  REQUEST_STUFFING.TGL_REQUEST AS TGL_REQUEST						  
				   FROM MASTER_CONTAINER  INNER JOIN CONTAINER_STUFFING ON MASTER_CONTAINER.NO_CONTAINER = CONTAINER_STUFFING.NO_CONTAINER JOIN REQUEST_STUFFING ON CONTAINER_STUFFING.NO_REQUEST = REQUEST_STUFFING.NO_REQUEST
                   WHERE MASTER_CONTAINER.NO_CONTAINER LIKE '%$no_cont%' AND LOCATION NOT LIKE 'GATO' AND AKTIF = 'Y'";
*/
$result			= $db->query($query);
$row			= $result->getAll();	

//print_r($row);

echo json_encode($row);


?>