<?php
if($_SESSION["LOGGED_STORAGE"] == NULL)
{
	exit();
}
$no_cont		= strtoupper($_GET["term"]);

$db 			= getDB("storage");
	
$query 			= "SELECT MASTER_CONTAINER.NO_CONTAINER,
			       MASTER_CONTAINER.SIZE_ AS SIZE_,
			       MASTER_CONTAINER.TYPE_ AS TYPE_,
			       MASTER_CONTAINER.NO_BOOKING,
			       MASTER_CONTAINER.COUNTER,
			       CONTAINER_STRIPPING.VIA AS VIA,
			       CONTAINER_STRIPPING.TGL_BONGKAR AS TGL_REQUEST,
			       CONTAINER_STRIPPING.NO_REQUEST AS NO_REQUEST,
			       REQUEST_STRIPPING.TGL_REQUEST AS TGL_REQUEST
			  FROM MASTER_CONTAINER
			       INNER JOIN CONTAINER_STRIPPING
			          ON MASTER_CONTAINER.NO_CONTAINER = CONTAINER_STRIPPING.NO_CONTAINER
			       JOIN REQUEST_STRIPPING
			          ON CONTAINER_STRIPPING.NO_REQUEST = REQUEST_STRIPPING.NO_REQUEST
			       INNER JOIN PLACEMENT
			          ON CONTAINER_STRIPPING.NO_CONTAINER = PLACEMENT.NO_CONTAINER
			             AND REQUEST_STRIPPING.NO_REQUEST_RECEIVING =
			                    PLACEMENT.NO_REQUEST_RECEIVING
			 WHERE     CONTAINER_STRIPPING.NO_CONTAINER LIKE '%$no_cont%'
			       AND LOCATION = 'IN_YARD'
			       AND AKTIF = 'Y'
			       AND ROWNUM <=1 ";
$result			= $db->query($query);
$row			= $result->getAll();	

//print_r($row);

echo json_encode($row);


?>