<?php 
	$db = getDB("storage");
	$no_cont = $_POST["NO_CONT"];
	$db->query("UPDATE CONTAINER_RECEIVING SET CONTAINER_RECEIVING.AKTIF='T' WHERE CONTAINER_RECEIVING.NO_CONTAINER = '$no_cont'");
	$db->query("UPDATE CONTAINER_DELIVERY SET CONTAINER_DELIVERY.AKTIF='T' WHERE CONTAINER_DELIVERY.NO_CONTAINER = '$no_cont'");
	$db->query("UPDATE CONTAINER_STUFFING SET CONTAINER_STUFFING.AKTIF='T' WHERE CONTAINER_STUFFING.NO_CONTAINER = '$no_cont'");
	$db->query("UPDATE CONTAINER_STRIPPING SET CONTAINER_STRIPPING.AKTIF='T' WHERE CONTAINER_STRIPPING.NO_CONTAINER = '$no_cont'");
	$db->query("UPDATE CONTAINER_RELOKASI SET CONTAINER_RELOKASI.AKTIF='T' WHERE CONTAINER_RELOKASI.NO_CONTAINER = '$no_cont'");
	
	echo "sukses";
	//exit();
?>