<?php
	//header('Location: '.HOME .'static/error.htm');		
	$tl =  xliteTemplate('req_list.htm');

//-----------------paging
/*
	if(isset($_GET["page"]))
	{
		$page = $_GET["page"];	
	}
	else
	{
		$page = 1;	
	}
*/
//------------------------	
	
	$db = getDB("storage");

	$from  = $_POST['from'];
	$to    = $_POST['to'];
	
	$no_req   = $_POST['no_req'];
	
	if(isset($_POST["cari"]))
	{
		$query_list = "SELECT REQUEST_STRIPPING.NO_REQUEST, TO_CHAR( REQUEST_STRIPPING.TGL_REQUEST,'dd/mm/yyyy') TGL_REQUEST, TO_CHAR( REQUEST_STRIPPING.TGL_REQUEST + 3,'dd/mm/yyyy') AS TGL_REQUEST_END, emkl.NAMA AS NAMA_EMKL, pnmt.NAMA AS NAMA_PNMT, COUNT(CONTAINER_STRIPPING.NO_CONTAINER) TOTAL, NVL(REQUEST_STRIPPING.PERP_DARI,'---') AS EX_REQ, REQUEST_STRIPPING.PERP_KE
				FROM REQUEST_STRIPPING INNER JOIN MASTER_PBM emkl ON REQUEST_STRIPPING.ID_EMKL = emkl.ID 
				JOIN MASTER_PBM pnmt ON REQUEST_STRIPPING.ID_PEMILIK = pnmt.ID 
				JOIN CONTAINER_STRIPPING ON REQUEST_STRIPPING.NO_REQUEST = CONTAINER_STRIPPING.NO_REQUEST AND 'Y' = CONTAINER_STRIPPING.AKTIF
				JOIN NOTA_STRIPPING ON REQUEST_STRIPPING.NO_REQUEST = NOTA_STRIPPING.NO_REQUEST AND 'YES' = LUNAS				
				WHERE (REQUEST_STRIPPING.TGL_REQUEST 
				BETWEEN TO_DATE('$from', 'dd/mm/yyyy') AND 
				TO_DATE('$to', 'dd/mm/yyyy') ) OR
				REQUEST_STRIPPING.NO_REQUEST LIKE '%%'
				GROUP BY REQUEST_STRIPPING.NO_REQUEST, TO_CHAR( REQUEST_STRIPPING.TGL_REQUEST,'dd/mm/yyyy'), TO_CHAR( REQUEST_STRIPPING.TGL_REQUEST + 3,'dd/mm/yyyy'), emkl.NAMA, pnmt.NAMA, REQUEST_STRIPPING.PERP_DARI, REQUEST_STRIPPING.PERP_KE
				ORDER BY REQUEST_STRIPPING.NO_REQUEST DESC";
	}
	else
	{
		$query_list = "SELECT REQUEST_STRIPPING.NO_REQUEST, TO_CHAR( REQUEST_STRIPPING.TGL_AWAL,'dd/mm/yyyy') TGL_REQUEST, TO_CHAR( REQUEST_STRIPPING.TGL_AKHIR,'dd/mm/yyyy') AS TGL_REQUEST_END, emkl.NAMA AS NAMA_EMKL, pnmt.NAMA AS NAMA_PNMT, COUNT(CONTAINER_STRIPPING.NO_CONTAINER) TOTAL, NVL(REQUEST_STRIPPING.PERP_DARI,'---') AS EX_REQ, REQUEST_STRIPPING.PERP_KE
				FROM REQUEST_STRIPPING 
				INNER JOIN V_MST_PBM emkl ON REQUEST_STRIPPING.KD_CONSIGNEE = emkl.KD_PBM 
				JOIN V_MST_PBM pnmt ON REQUEST_STRIPPING.KD_PENUMPUKAN_OLEH = pnmt.KD_PBM 
				JOIN CONTAINER_STRIPPING ON REQUEST_STRIPPING.NO_REQUEST = CONTAINER_STRIPPING.NO_REQUEST AND 'Y' = CONTAINER_STRIPPING.AKTIF
				JOIN NOTA_STRIPPING ON REQUEST_STRIPPING.NO_REQUEST = NOTA_STRIPPING.NO_REQUEST AND 'YES' = LUNAS
				WHERE REQUEST_STRIPPING.TGL_REQUEST 
				BETWEEN TRUNC(SYSDATE,'MONTH') AND LAST_DAY(SYSDATE) 
				GROUP BY REQUEST_STRIPPING.NO_REQUEST, TO_CHAR( REQUEST_STRIPPING.TGL_REQUEST,'dd/mm/yyyy'), emkl.NAMA, pnmt.NAMA,  TO_CHAR( REQUEST_STRIPPING.TGL_AKHIR,'dd/mm/yyyy'), REQUEST_STRIPPING.PERP_DARI, REQUEST_STRIPPING.PERP_KE
				ORDER BY REQUEST_STRIPPING.NO_REQUEST DESC";
	}

	$result_list	= $db->query($query_list);
	$row_list       = $result_list->getAll(); 
		
	
	$tl->assign("row_list",$row_list);
	$tl->assign("HOME",HOME);
	$tl->assign("APPID",APPID);
	
	$tl->renderToScreen();
?>
