<?php
	//header('Location: '.HOME .'static/error.htm');		
	$tl =  xliteTemplate('req_list.htm');

//-----------------paging
/*
	if(isset($_GET["page"]))
	{
		$page = $_GET["page"];	
	}
	else
	{
		$page = 1;	
	}
*/
//------------------------	
	
	$db = getDB("storage");
	$cari = $_POST["cari"];
	$no_req = $_POST["no_req"];
	$from = $_POST["from"];
	$to = $_POST["to"];
	
	if($cari == "cari"){
		if($no_req != NULL && $from == NULL && $to == NULL){
			$query_list = "SELECT REQUEST_RELOKASI.NO_REQUEST, TO_CHAR(REQUEST_RELOKASI.TGL_REQUEST,'dd/mm/yy') TGL_REQUEST,
					YARD_AREA1.NAMA_YARD YARD_TUJUAN, YARD_AREA2.NAMA_YARD YARD_ASAL,
					(SELECT COUNT(CONTAINER_RELOKASI.NO_CONTAINER) FROM CONTAINER_RELOKASI 
					WHERE CONTAINER_RELOKASI.NO_REQUEST = REQUEST_RELOKASI.NO_REQUEST AND CONTAINER_RELOKASI.AKTIF = 'Y') BOX
					FROM REQUEST_RELOKASI  
					INNER JOIN YARD_AREA YARD_AREA1 ON REQUEST_RELOKASI.YARD_TUJUAN = YARD_AREA1.ID
					INNER JOIN YARD_AREA YARD_AREA2 ON REQUEST_RELOKASI.YARD_ASAL = YARD_AREA2.ID 
					WHERE ROWNUM <= 10 AND REQUEST_RELOKASI.NO_REQUEST = '$no_req'
					AND request_relokasi.KOREKSI = 'Y'
					ORDER BY REQUEST_RELOKASI.NO_REQUEST DESC";
		}
		else if($no_req == NULL && $from != NULL && $to != NULL){
			$query_list = "SELECT REQUEST_RELOKASI.NO_REQUEST, TO_CHAR(REQUEST_RELOKASI.TGL_REQUEST,'dd/mm/yy') TGL_REQUEST,
					YARD_AREA1.NAMA_YARD YARD_TUJUAN, YARD_AREA2.NAMA_YARD YARD_ASAL,
					(SELECT COUNT(CONTAINER_RELOKASI.NO_CONTAINER) FROM CONTAINER_RELOKASI 
					WHERE CONTAINER_RELOKASI.NO_REQUEST = REQUEST_RELOKASI.NO_REQUEST AND CONTAINER_RELOKASI.AKTIF = 'Y') BOX
					FROM REQUEST_RELOKASI  
					INNER JOIN YARD_AREA YARD_AREA1 ON REQUEST_RELOKASI.YARD_TUJUAN = YARD_AREA1.ID
					INNER JOIN YARD_AREA YARD_AREA2 ON REQUEST_RELOKASI.YARD_ASAL = YARD_AREA2.ID 
					WHERE ROWNUM <= 10 AND REQUEST_RELOKASI.TGL_REQUEST BETWEEN TO_DATE('$from','yy-mm-dd') AND TO_DATE('$to','yy-mm-dd')
						AND request_relokasi.KOREKSI = 'Y'
					ORDER BY REQUEST_RELOKASI.NO_REQUEST DESC";
		}
		else{
			$query_list = "SELECT REQUEST_RELOKASI.NO_REQUEST, TO_CHAR(REQUEST_RELOKASI.TGL_REQUEST,'dd/mm/yy') TGL_REQUEST,
					YARD_AREA1.NAMA_YARD YARD_TUJUAN, YARD_AREA2.NAMA_YARD YARD_ASAL,
					(SELECT COUNT(CONTAINER_RELOKASI.NO_CONTAINER) FROM CONTAINER_RELOKASI 
					WHERE CONTAINER_RELOKASI.NO_REQUEST = REQUEST_RELOKASI.NO_REQUEST AND CONTAINER_RELOKASI.AKTIF = 'Y') BOX
					FROM REQUEST_RELOKASI  
					INNER JOIN YARD_AREA YARD_AREA1 ON REQUEST_RELOKASI.YARD_TUJUAN = YARD_AREA1.ID
					INNER JOIN YARD_AREA YARD_AREA2 ON REQUEST_RELOKASI.YARD_ASAL = YARD_AREA2.ID 
					WHERE ROWNUM <= 10 AND REQUEST_RELOKASI.TGL_REQUEST BETWEEN TO_DATE('$from','yy-mm-dd') AND TO_DATE('$to','yy-mm-dd')
						AND request_relokasi.KOREKSI = 'Y'
					AND REQUEST_RELOKASI.NO_REQUEST = '$no_req'
					ORDER BY REQUEST_RELOKASI.NO_REQUEST DESC";
		}
	}
	else{
	
    
	/* $query_list = "SELECT REQUEST_RECEIVING.NO_REQUEST AS NO_REQ_REC, 
					TO_CHAR( REQUEST_RECEIVING.TGL_REQUEST,'dd/mm/yyyy') TGL_REQUEST_REC, 
					y_asal.NAMA_YARD AS YARD_ASAL, y_dest.NAMA_YARD AS YARD_DEST, 
					REQUEST_DELIVERY.NO_REQUEST AS NO_REQ_DEL, 
					TO_CHAR( REQUEST_DELIVERY.TGL_REQUEST,'dd/mm/yyyy') TGL_REQUEST_DEL, 
					(SELECT COUNT(1) FROM CONTAINER_DELIVERY WHERE NO_REQUEST = REQUEST_DELIVERY.NO_REQUEST AND AKTIF = 'Y') AS BOX 
					FROM REQUEST_DELIVERY INNER JOIN REQUEST_RECEIVING ON REQUEST_RECEIVING.EX_REQ_DELIVERY = REQUEST_DELIVERY.NO_REQUEST 
					JOIN YARD_AREA y_asal ON REQUEST_DELIVERY.ID_YARD = y_asal.ID 
					JOIN YARD_AREA y_dest ON REQUEST_RECEIVING.ID_YARD = y_dest.ID 
					WHERE REQUEST_DELIVERY.PERALIHAN = 'RELOKASI' 
					AND rownum <= 10
					ORDER BY REQUEST_DELIVERY.NO_REQUEST DESC"; */
	$query_list = "SELECT REQUEST_RELOKASI.NO_REQUEST, TO_CHAR(REQUEST_RELOKASI.TGL_REQUEST,'dd/mm/yy') TGL_REQUEST,
					YARD_AREA1.NAMA_YARD YARD_TUJUAN, YARD_AREA2.NAMA_YARD YARD_ASAL,
					(SELECT COUNT(CONTAINER_RELOKASI.NO_CONTAINER) FROM CONTAINER_RELOKASI 
					WHERE CONTAINER_RELOKASI.NO_REQUEST = REQUEST_RELOKASI.NO_REQUEST AND CONTAINER_RELOKASI.AKTIF = 'Y') BOX
					FROM REQUEST_RELOKASI  
					INNER JOIN YARD_AREA YARD_AREA1 ON REQUEST_RELOKASI.YARD_TUJUAN = YARD_AREA1.ID
					INNER JOIN YARD_AREA YARD_AREA2 ON REQUEST_RELOKASI.YARD_ASAL = YARD_AREA2.ID 
					WHERE ROWNUM <= 10
						AND request_relokasi.KOREKSI = 'Y'
					ORDER BY REQUEST_RELOKASI.NO_REQUEST DESC";
	
	}
		
	$result_list	= $db->query($query_list);
	$row_list       = $result_list->getAll(); 
		
	
	$tl->assign("row_list",$row_list);
	$tl->assign("HOME",HOME);
	$tl->assign("APPID",APPID);
	
	$tl->renderToScreen();
	
	function cek_cetak($no_req)
	{
		$db 		= getDB("storage");
		$query_cek	= "SELECT CETAK_KARTU FROM REQUEST_RELOKASI WHERE NO_REQUEST = '$no_req'";	
		$result_cek	= $db->query($query_cek);
		$row_cek 	= $result_cek->fetchRow();
		
		if($row_cek["CETAK_KARTU"] > 0)
		{
				echo 'KARTU SP2 SUDAH DICETAK';
				//echo '<a href="'.HOME.APPID.'/view?no_nota='.$no_nota.'" target="_blank"> EDIT </a> ';		
		}
		else
		{
			echo '<a href="'.HOME.APPID.'/view?no_req='.$no_req.'" target="_self"> EDIT </a> ';
		}
	}
?>
