<?php
$no_cont		= strtoupper($_GET["term"]);

$db 			= getDB("storage");

/* $query			= "SELECT DISTINCT MC.*, P.STATUS_CONT STATUS, P.TGL_UPDATE
                    FROM MASTER_CONTAINER MC
                    LEFT JOIN HISTORY_CONTAINER P ON MC.NO_CONTAINER = P.NO_CONTAINER
                    --AND MC.NO_BOOKING = P.NO_BOOKING 
					AND MC.COUNTER = P.COUNTER
                    WHERE MC.NO_CONTAINER = '$no_cont'
					--AND P.TGL_UPDATE = (SELECT MAX(TGL_UPDATE) FROM HISTORY_CONTAINER WHERE NO_CONTAINER = '$no_cont')
                    ORDER BY P.TGL_UPDATE DESC
					"; */
					
/* $query = "SELECT Q.NO_CONTAINER, Q.SIZE_, Q.TYPE_, Q.LOCATION, Q.TIME_, X.NM_KAPAL, X.VOYAGE_IN, Q.NO_BOOKING, Q.COUNTER,
CASE WHEN Q.NO_BOOKING LIKE 'BP%' THEN '[I]'
WHEN Q.NO_BOOKING LIKE 'VESSEL_%' THEN '[]'
ELSE '[E]'
END IE
FROM (SELECT DISTINCT MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, MAX(P.TGL_UPDATE) TIME_, P.COUNTER
                    FROM MASTER_CONTAINER MC
                    LEFT JOIN HISTORY_CONTAINER P ON MC.NO_CONTAINER = P.NO_CONTAINER                    
                    WHERE MC.NO_CONTAINER = '$no_cont' 
                    GROUP BY MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, P.COUNTER
                    ORDER BY TIME_ DESC) Q, 
(SELECT A.NM_KAPAL,  TM.BP_ID, A.VOYAGE_IN  FROM petikemas_cabang.v_pkk_cont A JOIN PETIKEMAS_CABANG.TTM_BP_CONT TM ON A.NO_UKK = TM.NO_UKK
UNION SELECT A.NM_KAPAL, TM.NO_BOOKING BP_ID, A.VOYAGE_IN FROM petikemas_cabang.v_pkk_cont A JOIN PETIKEMAS_CABANG.TTH_CONT_BOOKING TM ON A.NO_UKK = TM.NO_UKK) X
WHERE REPLACE(Q.NO_BOOKING, 'VESSEL_NOTHING', 'BSK100000023') = X.BP_ID"; */

$query = "
SELECT Q.NO_CONTAINER, Q.SIZE_, Q.TYPE_, Q.LOCATION, Q.TIME_, Q.NO_BOOKING, Q.COUNTER,
CASE WHEN Q.NO_BOOKING LIKE 'BP%' THEN '[I]'
WHEN Q.NO_BOOKING LIKE 'VESSEL_%' THEN '[]'
ELSE '[E]'
END IE
FROM (SELECT DISTINCT MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, MAX(P.TGL_UPDATE) TIME_, P.COUNTER --, P.KEGIATAN
                    FROM MASTER_CONTAINER MC
                    JOIN HISTORY_CONTAINER P ON MC.NO_CONTAINER = P.NO_CONTAINER                    
                    WHERE MC.NO_CONTAINER = '$no_cont' --AND P.KEGIATAN IN ('REQUEST RECEIVING','REQUEST DELIVERY')
                    GROUP BY MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, P.COUNTER --, P.KEGIATAN
                    ORDER BY TIME_ DESC) Q";

$result			= $db->query($query);
$row			= $result->getAll();	

echo json_encode($row);


?>