<?php
	//header('Location: '.HOME .'static/error.htm');		
	$tl 	=  xliteTemplate('nota_list.htm');
	
	$tgl_awal	= $_POST["tgl_awal"]; 
	$tgl_akhir	= $_POST["tgl_akhir"]; 
	$jenis		= $_POST["jenis"];
	$id_menu2 	= $_POST['id_menu2'];
	
	$jum = count($id_menu2);
	$orderby = 'ORDER BY ';
	for($i=0;$i<count($id_menu2);$i++){
		$orderby .= $id_menu2[$i];
		if($i != $jum-1){
			$orderby .= ",";
		}
		
	}
	//echo $jum; exit();
	if($jum  == 0){
		$orderby= "";
	}
	//echo $tgl_awal;die;
	$db 	= getDB("storage");
	
	/* $query_list_ 	= "SELECT * FROM (
					SELECT NO_NOTA, NOTA_STRIPPING.NO_REQUEST, TRUNC(TGL_NOTA) TGL_NOTA, 'STRIPPING'  AS KEGIATAN, EMKL, TO_CHAR(TOTAL_TAGIHAN, '999,999,999,999') TOTAL_TAGIHAN, STRIPPING_DARI ASAL
					FROM NOTA_STRIPPING INNER JOIN REQUEST_STRIPPING ON NOTA_STRIPPING.NO_REQUEST = REQUEST_STRIPPING.NO_REQUEST
					WHERE TRUNC(TGL_NOTA) > TO_DATE('$tgl_awal','yyyy-mm-dd') AND TRUNC(TGL_NOTA) < TO_DATE('$tgl_akhir','yyyy-mm-dd')  
					UNION
					SELECT NO_NOTA, NOTA_STUFFING.NO_REQUEST, TRUNC(TGL_NOTA) TGL_NOTA, 'STUFFING'  AS KEGIATAN, EMKL, TO_CHAR(TOTAL_TAGIHAN, '999,999,999,999') TOTAL_TAGIHAN, STUFFING_DARI ASAL
					FROM NOTA_STUFFING INNER JOIN REQUEST_STUFFING ON NOTA_STUFFING.NO_REQUEST = REQUEST_STUFFING.NO_REQUEST
					WHERE TRUNC(TGL_NOTA) > TO_DATE('$tgl_awal','yyyy-mm-dd') AND TRUNC(TGL_NOTA) < TO_DATE('$tgl_akhir','yyyy-mm-dd')) 
					WHERE KEGIATAN LIKE '%$jenis%'"; */
	if($jenis == 'STRIPPING'){
		$query_list_ = "SELECT DISTINCT CONTAINER_STRIPPING.NO_CONTAINER , MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, 'MTY' STATUS_CONT, REQUEST_STRIPPING.NO_REQUEST , REQUEST_STRIPPING.TGL_REQUEST,  V_MST_PBM.NM_PBM, 'STRIPPING' KEGIATAN, CONTAINER_STRIPPING.TGL_APPROVE,
                       TO_CHAR(CONTAINER_STRIPPING.TGL_REALISASI,'DD-MM-YYYY HH24:MI:SS') TGL_REALISASI, CONTAINER_STRIPPING.ID_USER_REALISASI, TO_CHAR(HISTORY_PLACEMENT.TGL_UPDATE,'DD-MM-YYYY HH24:MI:SS') TGL_PLACEMENT, 
                       MASTER_CONTAINER.NO_BOOKING, PKK.NM_KAPAL, MU.NAMA_LENGKAP, PKK.VOYAGE_IN
                       FROM REQUEST_STRIPPING INNER JOIN 
                       CONTAINER_STRIPPING ON REQUEST_STRIPPING.NO_REQUEST = CONTAINER_STRIPPING.NO_REQUEST
                       INNER JOIN MASTER_USER MU ON CONTAINER_STRIPPING.ID_USER_REALISASI = MU.ID
                       INNER JOIN MASTER_CONTAINER ON CONTAINER_STRIPPING.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                       INNER JOIN V_PKK_CONT PKK ON PKK.NO_BOOKING = MASTER_CONTAINER.NO_BOOKING
                       LEFT JOIN V_MST_PBM ON REQUEST_STRIPPING.KD_CONSIGNEE = V_MST_PBM.KD_PBM AND V_MST_PBM.KD_CABANG = '05'
                       LEFT JOIN HISTORY_PLACEMENT ON CONTAINER_STRIPPING.NO_CONTAINER  = HISTORY_PLACEMENT.NO_CONTAINER AND REQUEST_STRIPPING.NO_REQUEST_RECEIVING = HISTORY_PLACEMENT.NO_REQUEST
                       WHERE TO_DATE(CONTAINER_STRIPPING.TGL_REALISASI,'dd-mm-rrrr') BETWEEN TO_DATE('$tgl_awal','yyyy-mm-dd') AND TO_DATE('$tgl_akhir','yyyy-mm-dd') ".$orderby;
	} else if($jenis == 'STUFFING'){
		$query_list_ = "SELECT CONTAINER_STUFFING.NO_CONTAINER , MC.SIZE_, MC.TYPE_, 'FCL' STATUS_CONT,  REQUEST_STUFFING.NO_REQUEST , REQUEST_STUFFING.TGL_REQUEST, V_MST_PBM.NM_PBM, 'STUFFING' KEGIATAN, CONTAINER_STUFFING.TGL_APPROVE, 
                       TO_CHAR(CONTAINER_STUFFING.TGL_REALISASI,'DD-MM-YYYY HH24:MI:SS') TGL_REALISASI, CONTAINER_STUFFING.ID_USER_REALISASI, TO_CHAR(HISTORY_PLACEMENT.TGL_UPDATE,'DD-MM-YYYY HH24:MI:SS') TGL_PLACEMENT, REQUEST_STUFFING.NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_IN, MU.NAMA_LENGKAP
                       FROM REQUEST_STUFFING INNER JOIN 
                       CONTAINER_STUFFING ON REQUEST_STUFFING.NO_REQUEST = CONTAINER_STUFFING.NO_REQUEST
                       INNER JOIN MASTER_USER MU ON CONTAINER_STUFFING.ID_USER_REALISASI = MU.ID
                       INNER JOIN MASTER_CONTAINER MC ON CONTAINER_STUFFING.NO_CONTAINER = MC.NO_CONTAINER
                       INNER JOIN V_PKK_CONT VB ON REQUEST_STUFFING.NO_BOOKING = VB.NO_BOOKING
                       LEFT JOIN V_MST_PBM ON REQUEST_STUFFING.KD_CONSIGNEE = V_MST_PBM.KD_PBM AND V_MST_PBM.KD_CABANG = '05'
                       LEFT JOIN HISTORY_PLACEMENT ON CONTAINER_STUFFING.NO_CONTAINER  = HISTORY_PLACEMENT.NO_CONTAINER AND REQUEST_STUFFING.NO_REQUEST_RECEIVING = HISTORY_PLACEMENT.NO_REQUEST
                        WHERE TO_DATE(CONTAINER_STUFFING.TGL_REALISASI,'dd-mm-rrrr') BETWEEN TO_DATE('$tgl_awal','yyyy-mm-dd') AND TO_DATE('$tgl_akhir','yyyy-mm-dd') ".$orderby;
	}
	

	 
	/* $query_list_ 	= " SELECT * FROM (
                       SELECT CONTAINER_STUFFING.NO_CONTAINER , REQUEST_STUFFING.NO_REQUEST , REQUEST_STUFFING.TGL_REQUEST, V_MST_PBM.NM_PBM, 'STUFFING' KEGIATAN, CONTAINER_STUFFING.TGL_APPROVE, 
                       CONTAINER_STUFFING.TGL_REALISASI, PLACEMENT.TGL_PLACEMENT
                       FROM REQUEST_STUFFING INNER JOIN 
                       CONTAINER_STUFFING ON REQUEST_STUFFING.NO_REQUEST = CONTAINER_STUFFING.NO_REQUEST
                       LEFT JOIN V_MST_PBM ON REQUEST_STUFFING.KD_CONSIGNEE = V_MST_PBM.KD_PBM
                       LEFT JOIN PLACEMENT ON CONTAINER_STUFFING.NO_CONTAINER  = PLACEMENT.NO_CONTAINER AND REQUEST_STUFFING.NO_REQUEST_RECEIVING = PLACEMENT.NO_REQUEST_RECEIVING
                       WHERE TRUNC(CONTAINER_STUFFING.TGL_APPROVE) BETWEEN TO_DATE('$tgl_awal','yyyy-mm-dd') AND TO_DATE('$tgl_akhir','yyyy-mm-dd')  
                       UNION
                       SELECT DISTINCT CONTAINER_STRIPPING.NO_CONTAINER , REQUEST_STRIPPING.NO_REQUEST , REQUEST_STRIPPING.TGL_REQUEST,  V_MST_PBM.NM_PBM, 'STRIPPING' KEGIATAN, CONTAINER_STRIPPING.TGL_APPROVE,
                       CONTAINER_STRIPPING.TGL_REALISASI, PLACEMENT.TGL_PLACEMENT
                       FROM REQUEST_STRIPPING INNER JOIN 
                       CONTAINER_STRIPPING ON REQUEST_STRIPPING.NO_REQUEST = CONTAINER_STRIPPING.NO_REQUEST
                       LEFT JOIN V_MST_PBM ON REQUEST_STRIPPING.KD_CONSIGNEE = V_MST_PBM.KD_PBM
                       LEFT JOIN PLACEMENT ON CONTAINER_STRIPPING.NO_CONTAINER  = PLACEMENT.NO_CONTAINER AND REQUEST_STRIPPING.NO_REQUEST_RECEIVING = PLACEMENT.NO_REQUEST_RECEIVING
                       WHERE TRUNC(CONTAINER_STRIPPING.TGL_APPROVE) BETWEEN TO_DATE('$tgl_awal','yyyy-mm-dd') AND TO_DATE('$tgl_akhir','yyyy-mm-dd')) A  
                       WHERE A.KEGIATAN LIKE '%$jenis%' ORDER BY NO_REQUEST DESC "; */
						   
	//echo $query_list_;
	$result_list_	= $db->query($query_list_);
	$row_list		= $result_list_->getAll(); 

	
	$tl->assign("row_list",$row_list);
	$tl->assign("tgl_awal",$tgl_awal);
	$tl->assign("tgl_akhir",$tgl_akhir);
	$tl->assign("HOME",HOME);
	$tl->assign("APPID",APPID);
	
	$tl->renderToScreen();
?>
