<?php 
	$tl	=  xliteTemplate('info.htm');
	$db = getDB("storage");
	$qselect = "SELECT A.NO, A.KEGIATAN, A.JUMLAH H,  B. JUMLAH H1 , C. JUMLAH H2, D. JUMLAH H3 FROM
				(SELECT 1 NO, 'KAPASITAS' KEGIATAN , 100 JUMLAH FROM CONTAINER_STUFFING
				UNION
				SELECT 2 NO ,'BERJALAN' KEGIATAN , count(NO_CONTAINER) JUMLAH FROM CONTAINER_STUFFING WHERE SYSDATE BETWEEN TGL_MULAI AND TGL_MULAI+5
				UNION
				SELECT 3 NO, 'SELESAI' KEGIATAN , count(NO_CONTAINER) JUMLAH FROM CONTAINER_STUFFING WHERE SYSDATE = TGL_MULAI+5) A,
				(SELECT 1 NO, 'KAPASITAS' KEGIATAN , 100 JUMLAH FROM CONTAINER_STUFFING
				UNION
				SELECT 2 NO ,'BERJALAN' KEGIATAN , count(NO_CONTAINER) JUMLAH FROM CONTAINER_STUFFING WHERE SYSDATE+1 BETWEEN TGL_MULAI AND TGL_MULAI+5
				UNION
				SELECT 3 NO, 'SELESAI' KEGIATAN , count(NO_CONTAINER) JUMLAH FROM CONTAINER_STUFFING WHERE SYSDATE+1 = TGL_MULAI+5) B,
				(SELECT 1 NO, 'KAPASITAS' KEGIATAN , 100 JUMLAH FROM CONTAINER_STUFFING
				UNION
				SELECT 2 NO ,'BERJALAN' KEGIATAN , count(NO_CONTAINER) JUMLAH FROM CONTAINER_STUFFING WHERE SYSDATE+2 BETWEEN TGL_MULAI AND TGL_MULAI+5
				UNION
				SELECT 3 NO, 'SELESAI' KEGIATAN , count(NO_CONTAINER) JUMLAH FROM CONTAINER_STUFFING WHERE SYSDATE+2 = TGL_MULAI+5) C,
				(SELECT 1 NO, 'KAPASITAS' KEGIATAN , 100 JUMLAH FROM CONTAINER_STUFFING
				UNION
				SELECT 2 NO ,'BERJALAN' KEGIATAN , count(NO_CONTAINER) JUMLAH FROM CONTAINER_STUFFING WHERE SYSDATE+3 BETWEEN TGL_MULAI AND TGL_MULAI+5
				UNION
				SELECT 3 NO, 'SELESAI' KEGIATAN , count(NO_CONTAINER) JUMLAH FROM CONTAINER_STUFFING WHERE SYSDATE+3 = TGL_MULAI+5) D
				WHERE A.NO = B.NO AND B.NO = C.NO AND C.NO = D.NO";
	$result = $db->query($qselect);
	
	
	$tanggalx = "SELECT TO_CHAR(SYSDATE,'dd/mm/yyyy') H, TO_CHAR(SYSDATE+1,'dd/mm/yyyy') H_1, TO_CHAR(SYSDATE+2,'dd/mm/yyyy') H_2, TO_CHAR(SYSDATE+3,'dd/mm/yyyy') H_3 FROM DUAL";
	$result_ = $db->query($tanggalx);
	
	$rows = $result->getAll();
	$tanggal_ = $result_->fetchRow();	
	$tl->assign('tanggal', $tanggal_);
	$tl->assign('row', $rows);
	$tl->renderToScreen();
?>