<?php
	$tl 	=  xliteTemplate('dwelling_list.htm');
	$id_area = $_GET["lokasi"];
	$mlo = $_GET["mlo"];
	$status = $_GET["status"];
	$db 	= getDB("storage"); 
	if($mlo == 'Y')
	{	
		$qplacement = "SELECT P.NO_CONTAINER, M.SIZE_ , M.TYPE_, P.STATUS, P.NO_REQUEST_RECEIVING,P.TGL_PLACEMENT, B.TGL_IN TANGGAL_OUT,
						SYSDATE TGL_CETAK, BA.NAME BLOK_, P.SLOT_, P.ROW_, P.TIER_, Y.NAMA_YARD LAPANGAN, 'GATE 06' GATE,
						TO_DATE (TO_CHAR (P.TGL_PLACEMENT, 'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') - TO_DATE(TO_CHAR(B.TGL_IN,'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') DWELLING
						FROM BORDER_GATE_OUT B, PLACEMENT P, MASTER_CONTAINER M, BLOCKING_AREA BA, YARD_AREA Y, HISTORY_CONTAINER H
						WHERE P.NO_CONTAINER = B.NO_CONTAINER
						AND P.NO_REQUEST_RECEIVING = B.NO_REQUEST
						AND P.ID_BLOCKING_AREA = BA.ID
						AND BA.ID_YARD_AREA = Y.ID
						AND H.NO_CONTAINER = P.NO_CONTAINER
						AND H.KEGIATAN = 'REQUEST DELIVERY'
						AND Y.ID = '$id_area' AND M.MLO = 'MLO' AND P.STATUS='$status'
						UNION
						SELECT P.NO_CONTAINER, M.SIZE_ , M.TYPE_, P.STATUS, P.NO_REQUEST_RECEIVING,P.TGL_PLACEMENT, B.TGL_IN TANGGAL_OUT,
						SYSDATE TGL_CETAK, BA.NAME BLOK_, P.SLOT_, P.ROW_, P.TIER_, Y.NAMA_YARD LAPANGAN, 'GATE 08' GATE,
						TO_DATE (TO_CHAR (P.TGL_PLACEMENT, 'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') - TO_DATE(TO_CHAR(B.TGL_IN,'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') DWELLING
						FROM GATE_OUT B, PLACEMENT P, MASTER_CONTAINER M, BLOCKING_AREA BA, YARD_AREA Y, HISTORY_CONTAINER H
						WHERE P.NO_CONTAINER = B.NO_CONTAINER
						AND P.NO_REQUEST_RECEIVING = B.NO_REQUEST
						AND P.ID_BLOCKING_AREA = BA.ID
						AND BA.ID_YARD_AREA = Y.ID
						AND H.NO_CONTAINER = P.NO_CONTAINER
						AND H.KEGIATAN = 'REQUEST DELIVERY'
						AND Y.ID = '$id_area' AND M.MLO = 'MLO' AND P.STATUS='$status'
						ORDER BY NO_REQUEST_RECEIVING DESC ";

	/*	$qplacement = "SELECT PLACEMENT.NO_CONTAINER NO_CONTAINER, MASTER_CONTAINER.SIZE_ , MASTER_CONTAINER.TYPE_, 
			  PLACEMENT.STATUS, PLACEMENT.NO_REQUEST_RECEIVING,  TRUNC(PLACEMENT.TGL_PLACEMENT) TGL_PLACEMENT, SYSDATE TGL_CETAK, 
			  BLOCKING_AREA.NAME BLOK_, PLACEMENT.SLOT_, PLACEMENT.ROW_, PLACEMENT.TIER_, TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') -TO_DATE (TO_CHAR (PLACEMENT.TGL_PLACEMENT, 'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') DWELLING, YARD_AREA.NAMA_YARD LAPANGAN
			  FROM PLACEMENT INNER JOIN MASTER_CONTAINER
			  ON PLACEMENT.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
		      INNER JOIN BLOCKING_AREA ON PLACEMENT.ID_BLOCKING_AREA = BLOCKING_AREA.ID
			  INNER JOIN YARD_AREA ON BLOCKING_AREA.ID_YARD_AREA = YARD_AREA.ID
			  WHERE YARD_AREA.ID = '$id_area' AND MASTER_CONTAINER.MLO = 'MLO' AND PLACEMENT.STATUS='$status' ORDER BY NO_REQUEST_RECEIVING DESC"; */
	}
	else if($mlo == 'T')
	{
		$qplacement = "SELECT P.NO_CONTAINER, M.SIZE_ , M.TYPE_, P.STATUS, P.NO_REQUEST_RECEIVING,P.TGL_PLACEMENT, B.TGL_IN TANGGAL_OUT,
						SYSDATE TGL_CETAK, BA.NAME BLOK_, P.SLOT_, P.ROW_, P.TIER_, Y.NAMA_YARD LAPANGAN, 'GATE 06' GATE,
						TO_DATE (TO_CHAR (P.TGL_PLACEMENT, 'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') - TO_DATE(TO_CHAR(B.TGL_IN,'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') DWELLING
						FROM BORDER_GATE_OUT B, PLACEMENT P, MASTER_CONTAINER M, BLOCKING_AREA BA, YARD_AREA Y, HISTORY_CONTAINER H
						WHERE P.NO_CONTAINER = B.NO_CONTAINER
						AND P.NO_REQUEST_RECEIVING = B.NO_REQUEST
						AND P.ID_BLOCKING_AREA = BA.ID
						AND BA.ID_YARD_AREA = Y.ID
						AND H.NO_CONTAINER = P.NO_CONTAINER
						AND H.KEGIATAN = 'REQUEST DELIVERY'
						AND Y.ID = '$id_area' AND M.MLO NOT IN (SELECT NO_CONTAINER FROM MASTER_CONTAINER WHERE MLO = 'MLO') AND 
						P.STATUS='$status' 
						UNION
						SELECT P.NO_CONTAINER, M.SIZE_ , M.TYPE_, P.STATUS, P.NO_REQUEST_RECEIVING,P.TGL_PLACEMENT, B.TGL_IN TANGGAL_OUT,
						SYSDATE TGL_CETAK, BA.NAME BLOK_, P.SLOT_, P.ROW_, P.TIER_, Y.NAMA_YARD LAPANGAN,
						TO_DATE (TO_CHAR (P.TGL_PLACEMENT, 'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') - TO_DATE(TO_CHAR(B.TGL_IN,'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') DWELLING
						FROM GATE_OUT B, PLACEMENT P, MASTER_CONTAINER M, BLOCKING_AREA BA, YARD_AREA Y, HISTORY_CONTAINER H
						WHERE P.NO_CONTAINER = B.NO_CONTAINER
						AND P.NO_REQUEST_RECEIVING = B.NO_REQUEST
						AND P.ID_BLOCKING_AREA = BA.ID
						AND BA.ID_YARD_AREA = Y.ID
						AND H.NO_CONTAINER = P.NO_CONTAINER
						AND H.KEGIATAN = 'REQUEST DELIVERY'
						AND Y.ID = '$id_area' AND M.MLO NOT IN (SELECT NO_CONTAINER FROM MASTER_CONTAINER WHERE MLO = 'MLO') AND
						P.STATUS='$status' ORDER BY NO_REQUEST_RECEIVING DESC";

	/*	$qplacement = "SELECT PLACEMENT.NO_CONTAINER NO_CONTAINER, MASTER_CONTAINER.SIZE_ , MASTER_CONTAINER.TYPE_, 
			  PLACEMENT.STATUS, PLACEMENT.NO_REQUEST_RECEIVING,  TRUNC(PLACEMENT.TGL_PLACEMENT) TGL_PLACEMENT, SYSDATE TGL_CETAK, 
			  BLOCKING_AREA.NAME BLOK_, PLACEMENT.SLOT_, PLACEMENT.ROW_, PLACEMENT.TIER_, TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') -TO_DATE (TO_CHAR (PLACEMENT.TGL_PLACEMENT, 'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') DWELLING, YARD_AREA.NAMA_YARD LAPANGAN
			  FROM PLACEMENT INNER JOIN MASTER_CONTAINER
			  ON PLACEMENT.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
		      INNER JOIN BLOCKING_AREA ON PLACEMENT.ID_BLOCKING_AREA = BLOCKING_AREA.ID
			  INNER JOIN YARD_AREA ON BLOCKING_AREA.ID_YARD_AREA = YARD_AREA.ID
			  WHERE YARD_AREA.ID = '$id_area' AND MASTER_CONTAINER.NO_CONTAINER NOT IN (SELECT NO_CONTAINER FROM MASTER_CONTAINER WHERE MLO = 'MLO') AND PLACEMENT.STATUS='$status' ORDER BY NO_REQUEST_RECEIVING DESC"; */
	}
	else{
		$qplacement = "SELECT PLACEMENT.NO_CONTAINER NO_CONTAINER, MASTER_CONTAINER.SIZE_ , MASTER_CONTAINER.TYPE_, 
			  PLACEMENT.STATUS, PLACEMENT.NO_REQUEST_RECEIVING,  TRUNC(PLACEMENT.TGL_PLACEMENT) TGL_PLACEMENT, SYSDATE TGL_CETAK, 
			  BLOCKING_AREA.NAME BLOK_, PLACEMENT.SLOT_, PLACEMENT.ROW_, PLACEMENT.TIER_, TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') -TO_DATE (TO_CHAR (PLACEMENT.TGL_PLACEMENT, 'YYYYMMDD HH:MI:SS AM'),'YYYYMMDD HH:MI:SS AM') DWELLING, YARD_AREA.NAMA_YARD LAPANGAN
			  FROM PLACEMENT INNER JOIN MASTER_CONTAINER
			  ON PLACEMENT.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
		      INNER JOIN BLOCKING_AREA ON PLACEMENT.ID_BLOCKING_AREA = BLOCKING_AREA.ID
			  INNER JOIN YARD_AREA ON BLOCKING_AREA.ID_YARD_AREA = YARD_AREA.ID
			  WHERE YARD_AREA.ID = '$id_area' AND PLACEMENT.STATUS='$status' ORDER BY NO_REQUEST_RECEIVING DESC";
	}
	
	$rplace = $db->query($qplacement);
	$rowplace = $rplace->getAll();
	
	$tl->assign("rowplace",$rowplace);
	$tl->assign("HOME",HOME);
	$tl->assign("APPID",APPID);
	
	$tl->renderToScreen();
?>