<?php
$no_nota		= strtoupper($_GET["term"]);

$db 			= getDB("storage");
	
//echo "SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER FROM NOTA_ALL_H WHERE NO_NOTA LIKE '$no_nota%'";
$query 			= "SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'RECEIVING' KEGIATAN FROM NOTA_RECEIVING WHERE NO_NOTA = '$no_nota' AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NOTA_DELIVERY.NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, CASE WHEN DELIVERY_KE = 'LUAR' THEN 'DELIVERY_MTY' ELSE 
CASE WHEN JN_REPO = 'EMPTY' THEN 'RELOKASI_MTY_KE_TPK' ELSE 'RELOKASI_TPK_EKS_STUFFING' END END AS KEGIATAN FROM NOTA_DELIVERY, REQUEST_DELIVERY WHERE NOTA_DELIVERY.NO_REQUEST = REQUEST_DELIVERY.NO_REQUEST AND NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'STUFFING' KEGIATAN FROM NOTA_STUFFING WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'STRIPPING' KEGIATAN FROM NOTA_STRIPPING WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'RELOKASI_ANTAR_DEPO' KEGIATAN FROM NOTA_RELOKASI WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'RELOKASI_MTY_EKS_STRIPPING' KEGIATAN FROM NOTA_RELOKASI_MTY WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'PENUMPUKAN_SP2' KEGIATAN FROM NOTA_PNKN_DEL WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TGL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'BATAL_MUAT' KEGIATAN FROM NOTA_BATAL_MUAT WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')";
$result			= $db->query($query);
$row			= $result->getAll();	
 
//print_r($row);

echo json_encode($row);


?>