<?php
$no_cont		= strtoupper($_GET["term"]);

$db 			= getDB("storage");
$id_yard		= $_SESSION["IDYARD_STORAGE"];
$query		= "SELECT c.NAME, a.NO_CONTAINER,
								b.SIZE_, b.TYPE_ , d.STATUS_CONT STATUS, a.TIER_,
								a.SLOT_,a.ROW_, c.NAME
												FROM PLACEMENT a, MASTER_CONTAINER b, BLOCKING_AREA c, HISTORY_CONTAINER d WHERE 
												a.NO_CONTAINER = b.NO_CONTAINER
												AND b.NO_CONTAINER = d.NO_CONTAINER
												AND d.TGL_UPDATE = (SELECT MAX(TGL_UPDATE) FROM HISTORY_CONTAINER WHERE NO_CONTAINER = d.NO_CONTAINER)
												AND a.ID_BLOCKING_AREA = c.ID 
												AND UPPER(b.NO_CONTAINER) LIKE '%$no_cont%'
												AND b.LOCATION = 'IN_YARD'
												ORDER BY a.TIER_ DESC";
// $query 			= "SELECT MASTER_CONTAINER.*, 
                        // CONTAINER_RECEIVING.*, REQUEST_RECEIVING.TGL_REQUEST, CASE WHEN PERALIHAN IS NULL THEN 'RECEIVING MTY' ELSE REQUEST_RECEIVING.PERALIHAN END PERALIHAN
                    // FROM CONTAINER_RECEIVING INNER JOIN MASTER_CONTAINER ON CONTAINER_RECEIVING.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                    // INNER JOIN REQUEST_RECEIVING ON CONTAINER_RECEIVING.NO_REQUEST = REQUEST_RECEIVING.NO_REQUEST 
                    // AND CONTAINER_RECEIVING.AKTIF = 'Y' 
                    // WHERE MASTER_CONTAINER.LOCATION = 'GATI' 
                    // --AND CONTAINER_RECEIVING.DEPO_TUJUAN = '$id_yard' 
                    // AND UPPER(CONTAINER_RECEIVING.NO_CONTAINER) LIKE '%$no_cont%' AND CONTAINER_RECEIVING.STATUS_REQ IS NULL
                    // ORDER BY REQUEST_RECEIVING.TGL_REQUEST DESC";
$result			= $db->query($query);
$row			= $result->getAll();	

//print_r($row);

echo json_encode($row);


?>