<?php 
$tl = xliteTemplate("cont_info.htm");
$no_cont		= $_GET["NO_CONT"];
$db 			= getDB("storage");

$q_aktif_rec	= "SELECT NO_CONTAINER, 'RECEIVING' ASAL FROM CONTAINER_RECEIVING WHERE CONTAINER_RECEIVING.NO_CONTAINER = '$no_cont' AND AKTIF = 'Y'
				UNION
				SELECT NO_CONTAINER, 'DELIVERY' ASAL FROM CONTAINER_DELIVERY WHERE CONTAINER_DELIVERY.NO_CONTAINER = '$no_cont' AND AKTIF = 'Y'
				UNION
				SELECT NO_CONTAINER, 'STUFFING' ASAL FROM CONTAINER_STUFFING WHERE CONTAINER_STUFFING.NO_CONTAINER = '$no_cont' AND AKTIF = 'Y'
				UNION
				SELECT NO_CONTAINER, 'STRIPPING' ASAL FROM CONTAINER_STRIPPING WHERE CONTAINER_STRIPPING.NO_CONTAINER = '$no_cont' AND AKTIF = 'Y'
				UNION
				SELECT NO_CONTAINER, 'RELOKASI' ASAL FROM CONTAINER_RELOKASI WHERE CONTAINER_RELOKASI.NO_CONTAINER = '$no_cont' AND AKTIF = 'Y'
				
";


$res_rec = $db->query($q_aktif_rec);
$row_rec = $res_rec->getAll();
$tl->assign('row_rec',$row_rec);
$tl->renderToScreen();

?>