<?php
$no_nota		= strtoupper($_GET["term"]);

$db 			= getDB("storage");
	
//echo "SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER FROM NOTA_ALL_H WHERE NO_NOTA LIKE '$no_nota%'";
$query 			= "SELECT NO_REQUEST, 'DELIVERY' KEGIATAN FROM REQUEST_DELIVERY WHERE NO_REQUEST LIKE '%$no_nota%'
UNION
SELECT NO_REQUEST, 'STRIPPING' KEGIATAN FROM REQUEST_STRIPPING WHERE NO_REQUEST LIKE '%$no_nota%'
UNION
SELECT NO_REQUEST, 'STUFFING' KEGIATAN FROM REQUEST_STUFFING WHERE NO_REQUEST LIKE '%$no_nota%'
UNION
SELECT NO_REQUEST, 'RECEIVING' KEGIATAN FROM REQUEST_RECEIVING WHERE NO_REQUEST LIKE '%$no_nota%'
UNION
SELECT NO_REQUEST, 'RELOKASI' KEGIATAN FROM REQUEST_RECEIVING WHERE NO_REQUEST LIKE '%$no_nota%'
";
$result			= $db->query($query);
$row			= $result->getAll();	
 
//print_r($row);

echo json_encode($row);


?>