<?php
	$db = getDB("storage");
	$no_cont = $_POST["NO_CONTAINER"];
	$query_handling = "SELECT MC.NO_CONTAINER, PL.STATUS, HC.KEGIATAN, HC.TGL_UPDATE, HC.NO_BOOKING NO_BOOKING, RR.NO_REQUEST NO_REQ_REC, 
            RST.NO_REQUEST NO_REQ_STR, RD.NO_REQUEST NO_REQ_DEL, RSF.NO_REQUEST NO_REQ_STF
            FROM MASTER_CONTAINER MC INNER JOIN HISTORY_CONTAINER HC
            ON MC.NO_CONTAINER = HC.NO_CONTAINER 
            AND MC.NO_BOOKING = HC.NO_BOOKING
            AND MC.COUNTER = HC.COUNTER
            LEFT JOIN REQUEST_RECEIVING RR
            ON RR.NO_REQUEST = HC.NO_REQUEST
            LEFT JOIN REQUEST_STRIPPING RST
            ON RST.NO_REQUEST = HC.NO_REQUEST
            LEFT JOIN REQUEST_DELIVERY RD
            ON RD.NO_REQUEST = HC.NO_REQUEST
            LEFT JOIN REQUEST_STUFFING RSF
            ON RSF.NO_REQUEST = HC.NO_REQUEST
            LEFT JOIN PLACEMENT PL ON PL.NO_CONTAINER = HC.NO_CONTAINER
            WHERE MC.NO_CONTAINER = '$no_cont'"; 
			
	$result = $db->query($query_handling);
	$rows = $result->getAll();


?>