<?php
$tl =  xliteTemplate('print_pontianak_new.htm');

$db			= getDB("storage");
//$no_nota	= $_GET["no_nota"];
$no_req		= $_GET["no_req"];

// debug($no_req);die;

$query_update_kartu = "UPDATE REQUEST_DELIVERY
					SET CETAK_KARTU = CETAK_KARTU +1
				WHERE NO_REQUEST = '$no_req'";
// echo $query_update_kartu;die;				
				
$db->query($query_update_kartu);
$query_rec_dari = "SELECT STATUS, CASE JN_REPO WHEN 'EKS_STUFFING' THEN 'EKS STUFFING'
					ELSE 'REPO MTY' END JN_REPO, O_IDVSB
				FROM REQUEST_DELIVERY
				WHERE NO_REQUEST = '$no_req' ";

$result_rec_dari = $db->query($query_rec_dari);
$row_rec_dari = $result_rec_dari->fetchRow();
$rec_dari = $row_rec_dari["JN_REPO"];
// echo $row_rec_dari;die;
//echo $row_rec_dari["JN_REPO"]; die;
if($row_rec_dari["O_IDVSB"] != ''){
    if($rec_dari=="EKS STUFFING")
{
	 
	   $query_nota =  "SELECT NOTA_DELIVERY.NO_NOTA, TO_CHAR(NOTA_DELIVERY.TGL_NOTA, 'DD-MM-YYYY') TGL_NOTA, V_MST_PBM.NM_PBM EMKL, REQ.NO_REQUEST, 
                    CONTAINER_DELIVERY.NO_CONTAINER,
                    MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, 'FCL' STATUS, REQ.CETAK_KARTU, 
                    REQ.JN_REPO, YARD_AREA.NAMA_YARD, MASTER_CONTAINER.NO_BOOKING NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_OUT, 
                    --TO_CHAR(VB.DOC_CLOSING_DATE_DRY,'dd/mm/rrrr hh24:mi:ss') TGL_JAM_CLOSE,
                    CONTAINER_DELIVERY.VIA
                    FROM NOTA_DELIVERY INNER JOIN REQUEST_DELIVERY REQ ON NOTA_DELIVERY.NO_REQUEST = REQ.NO_REQUEST
                    INNER JOIN CONTAINER_DELIVERY ON REQ.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                     INNER JOIN HISTORY_CONTAINER ON HISTORY_CONTAINER.NO_CONTAINER = CONTAINER_DELIVERY.NO_CONTAINER
                    AND HISTORY_CONTAINER.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                    AND HISTORY_CONTAINER.KEGIATAN = 'REQUEST DELIVERY'
                    INNER JOIN MASTER_CONTAINER ON CONTAINER_DELIVERY.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                    LEFT JOIN v_mst_pbm V_MST_PBM ON REQ.KD_EMKL = V_MST_PBM.KD_PBM and V_MST_PBM.kd_cabang = '05'
                    LEFT JOIN YARD_AREA ON CONTAINER_DELIVERY.ID_YARD = YARD_AREA.ID
                    INNER JOIN v_pkk_cont VB ON VB.NO_BOOKING = REQ.NO_BOOKING and vb.kd_cabang = '05'
                    WHERE NOTA_DELIVERY.TGL_NOTA = (SELECT MAX(NOTA.TGL_NOTA) FROM NOTA_DELIVERY NOTA WHERE NOTA.NO_REQUEST =  REQ.NO_REQUEST)
                    AND REQ.NO_REQUEST = '$no_req'";
		//echo $query_nota; 
		//die();		
					
        if($row_rec_dari["STATUS"] == 'AUTO_REPO'){

            $query_nota = " SELECT V_MST_PBM.NM_PBM EMKL, REQ.NO_REQUEST, 
                        CONTAINER_DELIVERY.NO_CONTAINER,
                        MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, 'MTY' STATUS, REQ.CETAK_KARTU, 
                        REQ.JN_REPO, YARD_AREA.NAMA_YARD, MASTER_CONTAINER.NO_BOOKING NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_OUT, 
                        --TO_CHAR(VB.DOC_CLOSING_DATE_DRY,'dd/mm/rrrr hh24:mi:ss') TGL_JAM_CLOSE,
                        CONTAINER_DELIVERY.VIA
                        FROM REQUEST_DELIVERY REQ INNER JOIN CONTAINER_DELIVERY ON REQ.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                          INNER JOIN HISTORY_CONTAINER ON HISTORY_CONTAINER.NO_CONTAINER = CONTAINER_DELIVERY.NO_CONTAINER
                        AND HISTORY_CONTAINER.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                        AND HISTORY_CONTAINER.KEGIATAN = 'REQUEST DELIVERY'
                        INNER JOIN MASTER_CONTAINER ON CONTAINER_DELIVERY.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                        LEFT JOIN v_mst_pbm V_MST_PBM ON REQ.KD_EMKL = V_MST_PBM.KD_PBM AND  V_MST_PBM.kd_cabang = '05'
                        LEFT JOIN YARD_AREA ON CONTAINER_DELIVERY.ID_YARD = YARD_AREA.ID
                        INNER JOIN v_pkk_cont VB ON VB.NO_BOOKING = REQ.NO_BOOKING and vb.kd_cabang = '05'
                        WHERE REQ.NO_REQUEST = '$no_req'";
			//echo $query_nota; 
			//die();			
        }
    }
    else if($rec_dari=="REPO MTY")
    {
        $query_nota =  "SELECT 
								NOTA_DELIVERY.NO_NOTA, 
								TO_CHAR(NOTA_DELIVERY.TGL_NOTA, 'DD-MM-YYYY') TGL_NOTA, V_MST_PBM.NM_PBM EMKL, 
								REQ.NO_REQUEST, 
								CONTAINER_DELIVERY.NO_CONTAINER,
								MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, CONTAINER_DELIVERY.STATUS, REQ.CETAK_KARTU, 
								REQ.JN_REPO, YARD_AREA.NAMA_YARD, MASTER_CONTAINER.NO_BOOKING NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_OUT, 
                        TO_CHAR(TO_DATE(AB.CLOSSING_TIME,'yyyymmddhh24miss'),'dd/mm/rrrr hh24:mi:ss') TGL_JAM_CLOSE, 
                        CONTAINER_DELIVERY.VIA
                        FROM NOTA_DELIVERY INNER JOIN REQUEST_DELIVERY REQ ON NOTA_DELIVERY.NO_REQUEST = REQ.NO_REQUEST
                        INNER JOIN CONTAINER_DELIVERY ON REQ.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                        INNER JOIN HISTORY_CONTAINER ON HISTORY_CONTAINER.NO_CONTAINER = CONTAINER_DELIVERY.NO_CONTAINER
                        AND HISTORY_CONTAINER.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                        AND HISTORY_CONTAINER.KEGIATAN = 'REQUEST DELIVERY'
                        INNER JOIN MASTER_CONTAINER ON CONTAINER_DELIVERY.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                        LEFT JOIN v_mst_pbm V_MST_PBM ON REQ.KD_EMKL = V_MST_PBM.KD_PBM and V_MST_PBM.kd_cabang = '05'
                        LEFT JOIN YARD_AREA ON CONTAINER_DELIVERY.ID_YARD = YARD_AREA.ID
                        INNER JOIN V_PKK_CONT VB ON VB.NO_BOOKING = REQ.NO_BOOKING and vb.kd_cabang = '05'
                        JOIN m_vsb_voyage@dbint_link AB ON TO_CHAR(AB.ID_VSB_VOYAGE) = VB.NO_UKK
                        WHERE NOTA_DELIVERY.TGL_NOTA = (SELECT MAX(NOTA.TGL_NOTA) FROM NOTA_DELIVERY NOTA WHERE NOTA.NO_REQUEST =  REQ.NO_REQUEST)
                        AND REQ.NO_REQUEST = '$no_req'";
						//echo $query_nota; 
						//die();

        if($row_rec_dari["STATUS"] == 'AUTO_REPO'){

            $query_nota = "SELECT V_MST_PBM.NM_PBM EMKL, REQ.NO_REQUEST, 
                        CONTAINER_DELIVERY.NO_CONTAINER,
                        MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, 'MTY' STATUS, REQ.CETAK_KARTU, 
                        REQ.JN_REPO, YARD_AREA.NAMA_YARD, MASTER_CONTAINER.NO_BOOKING NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_OUT, 
                        TO_CHAR(TO_DATE(AB.CLOSSING_TIME,'yyyymmddhh24miss'),'dd/mm/rrrr hh24:mi:ss') TGL_JAM_CLOSE, 
                        CONTAINER_DELIVERY.VIA
                        FROM REQUEST_DELIVERY REQ INNER JOIN CONTAINER_DELIVERY ON REQ.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                        INNER JOIN HISTORY_CONTAINER ON HISTORY_CONTAINER.NO_CONTAINER = CONTAINER_DELIVERY.NO_CONTAINER
                        AND HISTORY_CONTAINER.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                        AND HISTORY_CONTAINER.KEGIATAN = 'REQUEST DELIVERY'
                        INNER JOIN MASTER_CONTAINER ON CONTAINER_DELIVERY.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                        LEFT JOIN v_mst_pbm V_MST_PBM ON REQ.KD_EMKL = V_MST_PBM.KD_PBM AND  V_MST_PBM.kd_cabang = '05'
                        LEFT JOIN YARD_AREA ON CONTAINER_DELIVERY.ID_YARD = YARD_AREA.ID
                        INNER JOIN v_pkk_cont VB ON VB.NO_BOOKING = REQ.NO_BOOKING and vb.kd_cabang = '05'
                        JOIN m_vsb_voyage@dbint_link AB ON AB.ID_VSB_VOYAGE = VB.NO_UKK
                        WHERE REQ.NO_REQUEST = '$no_req'";
        }

}
}
else {
if($rec_dari=="EKS STUFFING")
{
	 
	 $query_nota =  "SELECT NOTA_DELIVERY.NO_NOTA, TO_CHAR(NOTA_DELIVERY.TGL_NOTA, 'DD-MM-YYYY') TGL_NOTA, V_MST_PBM.NM_PBM EMKL, REQ.NO_REQUEST, 
                    CONTAINER_DELIVERY.NO_CONTAINER,
                    MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, 'FCL' STATUS, REQ.CETAK_KARTU, 
                    REQ.JN_REPO, YARD_AREA.NAMA_YARD, MASTER_CONTAINER.NO_BOOKING NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_OUT, TO_CHAR(VB.TGL_JAM_TIBA,'dd/mm/rrrr hh24:mi:ss') TGL_JAM_CLOSE,
                    CONTAINER_DELIVERY.VIA
                    FROM NOTA_DELIVERY INNER JOIN REQUEST_DELIVERY REQ ON NOTA_DELIVERY.NO_REQUEST = REQ.NO_REQUEST
                    INNER JOIN CONTAINER_DELIVERY ON REQ.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                     INNER JOIN HISTORY_CONTAINER ON HISTORY_CONTAINER.NO_CONTAINER = CONTAINER_DELIVERY.NO_CONTAINER
                    AND HISTORY_CONTAINER.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                    AND HISTORY_CONTAINER.KEGIATAN = 'REQUEST DELIVERY'
                    INNER JOIN MASTER_CONTAINER ON CONTAINER_DELIVERY.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                    LEFT JOIN V_MST_PBM ON REQ.KD_EMKL = V_MST_PBM.KD_PBM and V_MST_PBM.kd_cabang = '05'
                    LEFT JOIN YARD_AREA ON CONTAINER_DELIVERY.ID_YARD = YARD_AREA.ID
                    INNER JOIN V_PKK_CONT VB ON VB.NO_BOOKING = REQ.NO_BOOKING and vb.kd_cabang = '05'
                    WHERE NOTA_DELIVERY.TGL_NOTA = (SELECT MAX(NOTA.TGL_NOTA) FROM NOTA_DELIVERY NOTA WHERE NOTA.NO_REQUEST =  REQ.NO_REQUEST)
                    AND REQ.NO_REQUEST = '$no_req'";
					
	if($row_rec_dari["STATUS"] == 'AUTO_REPO'){
		
		$query_nota = " SELECT V_MST_PBM.NM_PBM EMKL, REQ.NO_REQUEST, 
                    CONTAINER_DELIVERY.NO_CONTAINER,
                    MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, 'MTY' STATUS, REQ.CETAK_KARTU, 
                    REQ.JN_REPO, YARD_AREA.NAMA_YARD, MASTER_CONTAINER.NO_BOOKING NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_OUT, TO_CHAR(VB.DOC_CLOSING_DATE_DRY,'dd/mm/rrrr hh24:mi:ss') TGL_JAM_CLOSE,
                    CONTAINER_DELIVERY.VIA
                    FROM REQUEST_DELIVERY REQ INNER JOIN CONTAINER_DELIVERY ON REQ.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                      INNER JOIN HISTORY_CONTAINER ON HISTORY_CONTAINER.NO_CONTAINER = CONTAINER_DELIVERY.NO_CONTAINER
                    AND HISTORY_CONTAINER.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                    AND HISTORY_CONTAINER.KEGIATAN = 'REQUEST DELIVERY'
                    INNER JOIN MASTER_CONTAINER ON CONTAINER_DELIVERY.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                    LEFT JOIN KAPAL_CABANG.MST_PBM V_MST_PBM ON REQ.KD_EMKL = V_MST_PBM.KD_PBM AND  V_MST_PBM.kd_cabang = '05'
                    LEFT JOIN YARD_AREA ON CONTAINER_DELIVERY.ID_YARD = YARD_AREA.ID
                    INNER JOIN V_BOOKING_STACK_TPK VB ON VB.NO_BOOKING = REQ.NO_BOOKING and vb.kd_cabang = '05'
                    WHERE REQ.NO_REQUEST = '$no_req'";
	}
}
else if($rec_dari=="REPO MTY")
{
	$query_nota =  "SELECT NOTA_DELIVERY.NO_NOTA, TO_CHAR(NOTA_DELIVERY.TGL_NOTA, 'DD-MM-YYYY') TGL_NOTA, V_MST_PBM.NM_PBM EMKL, REQ.NO_REQUEST, 
			        CONTAINER_DELIVERY.NO_CONTAINER,
			        MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, 'MTY' STATUS, REQ.CETAK_KARTU, 
			        REQ.JN_REPO, YARD_AREA.NAMA_YARD, MASTER_CONTAINER.NO_BOOKING NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_OUT, 
			        TO_CHAR(VB.TGL_JAM_TIBA,'dd/mm/rrrr hh24:mi:ss') TGL_JAM_CLOSE, CONTAINER_DELIVERY.VIA
			        FROM NOTA_DELIVERY INNER JOIN REQUEST_DELIVERY REQ ON NOTA_DELIVERY.NO_REQUEST = REQ.NO_REQUEST
			        INNER JOIN CONTAINER_DELIVERY ON REQ.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
			        INNER JOIN HISTORY_CONTAINER ON HISTORY_CONTAINER.NO_CONTAINER = CONTAINER_DELIVERY.NO_CONTAINER
			        AND HISTORY_CONTAINER.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
			        AND HISTORY_CONTAINER.KEGIATAN = 'REQUEST DELIVERY'
			        INNER JOIN MASTER_CONTAINER ON CONTAINER_DELIVERY.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
			        LEFT JOIN V_MST_PBM ON REQ.KD_EMKL = V_MST_PBM.KD_PBM and V_MST_PBM.kd_cabang = '05'
			        LEFT JOIN YARD_AREA ON CONTAINER_DELIVERY.ID_YARD = YARD_AREA.ID
			        INNER JOIN V_PKK_CONT VB ON VB.NO_BOOKING = REQ.NO_BOOKING and vb.kd_cabang = '05'
			        WHERE NOTA_DELIVERY.TGL_NOTA = (SELECT MAX(NOTA.TGL_NOTA) FROM NOTA_DELIVERY NOTA WHERE NOTA.NO_REQUEST =  REQ.NO_REQUEST)
			        AND REQ.NO_REQUEST = '$no_req'";
					
	if($row_rec_dari["STATUS"] == 'AUTO_REPO'){
		
		$query_nota = "SELECT V_MST_PBM.NM_PBM EMKL, REQ.NO_REQUEST, 
                    CONTAINER_DELIVERY.NO_CONTAINER,
                    MASTER_CONTAINER.SIZE_, MASTER_CONTAINER.TYPE_, 'MTY' STATUS, REQ.CETAK_KARTU, 
                    REQ.JN_REPO, YARD_AREA.NAMA_YARD, MASTER_CONTAINER.NO_BOOKING NO_BOOKING, VB.NM_KAPAL, VB.VOYAGE_OUT, TO_CHAR(VB.DOC_CLOSING_DATE_DRY,'dd/mm/rrrr hh24:mi:ss') TGL_JAM_CLOSE, CONTAINER_DELIVERY.VIA
                    FROM REQUEST_DELIVERY REQ INNER JOIN CONTAINER_DELIVERY ON REQ.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                    INNER JOIN HISTORY_CONTAINER ON HISTORY_CONTAINER.NO_CONTAINER = CONTAINER_DELIVERY.NO_CONTAINER
                    AND HISTORY_CONTAINER.NO_REQUEST = CONTAINER_DELIVERY.NO_REQUEST
                    AND HISTORY_CONTAINER.KEGIATAN = 'REQUEST DELIVERY'
                    INNER JOIN MASTER_CONTAINER ON CONTAINER_DELIVERY.NO_CONTAINER = MASTER_CONTAINER.NO_CONTAINER
                    LEFT JOIN KAPAL_CABANG.MST_PBM V_MST_PBM ON REQ.KD_EMKL = V_MST_PBM.KD_PBM AND  V_MST_PBM.kd_cabang = '05'
                    LEFT JOIN YARD_AREA ON CONTAINER_DELIVERY.ID_YARD = YARD_AREA.ID
                    INNER JOIN V_BOOKING_STACK_TPK VB ON VB.NO_BOOKING = REQ.NO_BOOKING and vb.kd_cabang = '05'
                    WHERE REQ.NO_REQUEST = '$no_req'";
	}

}
}

if(isset($_GET['no_cont'])){
		$no_cont = $_GET['no_cont'];
		$query_nota .= " AND TRIM(CONTAINER_DELIVERY.NO_CONTAINER) = TRIM('$no_cont')";
}
     $query_nota .= "ORDER BY TGL_UPDATE ASC";
	$result_nota	= $db->query($query_nota);
	$row			= $result_nota->getAll();
$name 		= $_SESSION["NAME"]; 

$tl->assign('userid',$name);
$tl->assign('row',$row);
$tl->renderToScreen();
?>