<?php
$no_nota		= strtoupper($_GET["term"]);

$db 			= getDB("storage");
	
//echo "SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER FROM NOTA_ALL_H WHERE NO_NOTA LIKE '$no_nota%'";
$query 			= "SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'RECEIVING' KEGIATAN FROM NOTA_RECEIVING WHERE NO_NOTA = '$no_nota' AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER,'DELIVERY' KEGIATAN FROM NOTA_DELIVERY WHERE NO_NOTA = '$no_nota' AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'STUFFING' KEGIATAN FROM NOTA_STUFFING WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'STRIPPING' KEGIATAN FROM NOTA_STRIPPING WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'RELOKASI' KEGIATAN FROM NOTA_RELOKASI WHERE NO_NOTA = '$no_nota' AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'STRIPPING' KEGIATAN FROM NOTA_RELOKASI_MTY WHERE NO_NOTA = '$no_nota' AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER, 'PNKN_DEL' KEGIATAN FROM NOTA_PNKN_DEL WHERE NO_NOTA = '$no_nota' AND (STATUS = 'NEW' OR STATUS = 'PERP')
UNION
SELECT NO_NOTA, NO_REQUEST, EMKL, ALAMAT, NPWP, TOTAL_TAGIHAN, PPN, TAGIHAN TOTAL, NO_FAKTUR, TRANSFER, LUNAS, TO_CHAR(TANGGAL_LUNAS,'dd/mm/yyyy') TGL_LUNAS, NVL(TRANSFER, '-') TRANSFER,'PNKN_STUF' KEGIATAN FROM NOTA_PNKN_STUF WHERE NO_NOTA = '$no_nota' --AND (STATUS = 'NEW' OR STATUS = 'PERP')";
$result			= $db->query($query);
$row			= $result->getAll();	

//print_r($row);

echo json_encode($row);


?>