<?php

// $no_cont		= strtoupper($_GET["term"]);
$NO_CONTAINER		= strtoupper($_GET["NO_CONTAINER"]);

$db 			= getDB("storage");

/* $query			= "SELECT DISTINCT MC.*, P.STATUS_CONT STATUS, P.TGL_UPDATE
                    FROM MASTER_CONTAINER MC
                    LEFT JOIN HISTORY_CONTAINER P ON MC.NO_CONTAINER = P.NO_CONTAINER
                    --AND MC.NO_BOOKING = P.NO_BOOKING 
					AND MC.COUNTER = P.COUNTER
                    WHERE MC.NO_CONTAINER = '$no_cont'
					--AND P.TGL_UPDATE = (SELECT MAX(TGL_UPDATE) FROM HISTORY_CONTAINER WHERE NO_CONTAINER = '$no_cont')
                    ORDER BY P.TGL_UPDATE DESC
					"; */
					
/* $query = "SELECT Q.NO_CONTAINER, Q.SIZE_, Q.TYPE_, Q.LOCATION, Q.TIME_, X.NM_KAPAL, X.VOYAGE_IN, Q.NO_BOOKING, Q.COUNTER,
CASE WHEN Q.NO_BOOKING LIKE 'BP%' THEN '[I]'
WHEN Q.NO_BOOKING LIKE 'VESSEL_%' THEN '[]'
ELSE '[E]'
END IE
FROM (SELECT DISTINCT MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, MAX(P.TGL_UPDATE) TIME_, P.COUNTER
                    FROM MASTER_CONTAINER MC
                    LEFT JOIN HISTORY_CONTAINER P ON MC.NO_CONTAINER = P.NO_CONTAINER                    
                    WHERE MC.NO_CONTAINER = '$no_cont' 
                    GROUP BY MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, P.COUNTER
                    ORDER BY TIME_ DESC) Q, 
(SELECT A.NM_KAPAL,  TM.BP_ID, A.VOYAGE_IN  FROM petikemas_cabang.v_pkk_cont A JOIN PETIKEMAS_CABANG.TTM_BP_CONT TM ON A.NO_UKK = TM.NO_UKK
UNION SELECT A.NM_KAPAL, TM.NO_BOOKING BP_ID, A.VOYAGE_IN FROM petikemas_cabang.v_pkk_cont A JOIN PETIKEMAS_CABANG.TTH_CONT_BOOKING TM ON A.NO_UKK = TM.NO_UKK) X
WHERE REPLACE(Q.NO_BOOKING, 'VESSEL_NOTHING', 'BSK100000023') = X.BP_ID"; */

/* $query = "
SELECT Q.NO_CONTAINER, Q.SIZE_, Q.TYPE_, Q.LOCATION, Q.TIME_, Q.NO_BOOKING, Q.COUNTER,
CASE WHEN Q.NO_BOOKING LIKE 'BP%' THEN '[I]'
WHEN Q.NO_BOOKING LIKE 'VESSEL_%' THEN '[]'
ELSE '[E]'
END IE
FROM (SELECT DISTINCT MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, MAX(P.TGL_UPDATE) TIME_, P.COUNTER --, P.KEGIATAN
                    FROM MASTER_CONTAINER MC
                    JOIN HISTORY_CONTAINER P ON MC.NO_CONTAINER = P.NO_CONTAINER                    
                    WHERE MC.NO_CONTAINER = '$no_cont' --AND P.KEGIATAN IN ('REQUEST RECEIVING','REQUEST DELIVERY')
                    GROUP BY MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, P.COUNTER --, P.KEGIATAN
                    ORDER BY TIME_ DESC) Q"; */

// $query = "SELECT Q.NO_CONTAINER, Q.SIZE_, Q.TYPE_, Q.LOCATION, Q.TIME_, Q.NO_BOOKING, Q.COUNTER,
// CASE WHEN Q.NO_BOOKING LIKE 'BP%' THEN '[I]'
// WHEN Q.NO_BOOKING LIKE 'VESSEL_%' THEN 
//         CASE WHEN W.KEGIATAN = 'REQUEST RECEIVING' THEN  '[I]' ELSE '[E]' END
// ELSE '[E]'
// END IE, W.KEGIATAN
// FROM (SELECT DISTINCT MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, MAX(P.TGL_UPDATE) TIME_, P.COUNTER --, P.KEGIATAN
//                     FROM MASTER_CONTAINER MC
//                     JOIN HISTORY_CONTAINER P ON MC.NO_CONTAINER = P.NO_CONTAINER                    
//                     WHERE MC.NO_CONTAINER = '$no_cont' --AND P.KEGIATAN IN ('REQUEST RECEIVING','REQUEST DELIVERY')
//                     GROUP BY MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, P.COUNTER --, P.KEGIATAN
//                     ORDER BY TIME_ DESC) Q,  
// (SELECT NO_REQUEST,COUNTER, NO_BOOKING,KEGIATAN,NO_CONTAINER FROM HISTORY_CONTAINER) W
// WHERE Q.NO_BOOKING = W.NO_BOOKING(+)
// AND Q.COUNTER = W.COUNTER(+)
// AND Q.NO_CONTAINER = W.NO_CONTAINER(+)
// AND W.NO_BOOKING(+) = 'VESSEL_NOTHING'
// AND W.KEGIATAN(+) = 'REQUEST RECEIVING'";

$query = "SELECT * FROM (SELECT Q.NO_CONTAINER, Q.SIZE_, Q.TYPE_, Q.LOCATION, Q.TIME_, Q.NO_BOOKING, Q.COUNTER,
CASE WHEN Q.NO_BOOKING LIKE 'BP%' THEN '[I]'
WHEN Q.NO_BOOKING LIKE 'VESSEL_%' THEN 
        CASE WHEN W.KEGIATAN = 'REQUEST RECEIVING' THEN  '[I]' ELSE '[E]' END
ELSE '[E]'
END IE, W.KEGIATAN, Q.NM_KAPAL, Q.VOYAGE_IN
FROM (SELECT DISTINCT MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, MAX(P.TGL_UPDATE) TIME_, P.COUNTER , PK.NM_KAPAL, PK.VOYAGE_IN
                    FROM MASTER_CONTAINER MC
                    JOIN HISTORY_CONTAINER P ON MC.NO_CONTAINER = P.NO_CONTAINER
                    LEFT JOIN V_PKK_CONT PK ON REPLACE(P.NO_BOOKING, 'VESSEL_NOTHING', 'BSK100000023') = PK.NO_BOOKING                    
                    WHERE MC.NO_CONTAINER = '$NO_CONTAINER' 
                    GROUP BY MC.NO_CONTAINER, MC.SIZE_, MC.TYPE_, MC.LOCATION, P.NO_BOOKING, P.COUNTER, PK.NM_KAPAL, PK.VOYAGE_IN
                    ORDER BY TIME_ DESC) Q,  
(SELECT NO_REQUEST,COUNTER, NO_BOOKING,KEGIATAN,NO_CONTAINER FROM HISTORY_CONTAINER) W
WHERE Q.NO_BOOKING = W.NO_BOOKING(+)
AND Q.NO_BOOKING IS NOT NULL
AND Q.COUNTER = W.COUNTER(+)
AND Q.NO_CONTAINER = W.NO_CONTAINER(+)
AND W.NO_BOOKING(+) = 'VESSEL_NOTHING'
AND W.KEGIATAN(+) = 'REQUEST RECEIVING'
ORDER BY TIME_ DESC ) WHERE ROWNUM <= 6 ";

$result			= $db->query($query);
$row			= $result->getAll();	

echo json_encode($row);


?>