<?php

$nama			= strtoupper($_GET["term"]);

$db 			= getDB("storage");
	
/*$query 			= "select ID, NAMA from MASTER_PBM WHERE NAMA LIKE '%$nama%' "; */

$query 			= "SELECT * FROM (SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'RECEIVING' KEGIATAN, STATUS FROM nota_receiving WHERE NO_REQUEST LIKE '%$nama%'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'STUFFING' KEGIATAN, STATUS FROM nota_stuffing WHERE NO_REQUEST LIKE '%$nama%'
UNION 
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL,  'STRIPPING' KEGIATAN, STATUS  FROM nota_stripping WHERE NO_REQUEST LIKE '%$nama%'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL,  'DELIVERY' KEGIATAN, STATUS  FROM nota_delivery WHERE NO_REQUEST LIKE '%$nama%'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL,  'RELOKASI' KEGIATAN, STATUS  FROM nota_relokasi WHERE NO_REQUEST LIKE '%$nama%'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'BATALMUAT' KEGIATAN, STATUS FROM nota_batal_muat WHERE NO_REQUEST LIKE '%$nama%'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'RELOKASI_MTY' KEGIATAN, STATUS FROM nota_relokasi_mty WHERE NO_REQUEST LIKE '%$nama%'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'PNKN_DELIVERY' KEGIATAN, STATUS FROM nota_pnkn_del WHERE NO_REQUEST LIKE '%$nama%'
UNION
SELECT NO_NOTA, NO_FAKTUR, NO_REQUEST, EMKL, 'PNKN_STUFFING' KEGIATAN, STATUS FROM nota_pnkn_stuf WHERE NO_REQUEST LIKE '%$nama%') A
WHERE A.STATUS <> 'BATAL'
"; 

$result			= $db->query($query);
$row			= $result->getAll();	
//echo $query;
echo json_encode($row);


?>