<?php
$no_cont		= strtoupper($_GET["term"]);
$id_yard		= $_SESSION["IDYARD_STORAGE"];
$db 			= getDB("storage");
	
$query 			= "SELECT MASTER_CONTAINER.*, NVL(BLOCKING_AREA.NAME,'-') AS BLOCK, NVL(BLOCKING_AREA.ID,'0') AS BLOCK_ID, NVL(PLACEMENT.SLOT_,'0') AS SLOT_, NVL(PLACEMENT.ROW_,'0') AS ROW_, NVL(PLACEMENT.TIER_,'0') AS TIER_ FROM PLACEMENT RIGHT OUTER JOIN MASTER_CONTAINER ON MASTER_CONTAINER.NO_CONTAINER = PLACEMENT.NO_CONTAINER FULL OUTER JOIN BLOCKING_AREA ON PLACEMENT.ID_BLOCKING_AREA = BLOCKING_AREA.ID WHERE MASTER_CONTAINER.NO_CONTAINER LIKE '%$no_cont%' AND BLOCKING_AREA.ID_YARD_AREA = '$id_yard' AND MASTER_CONTAINER.LOCATION NOT LIKE 'GATO'";
$result			= $db->query($query);
$row			= $result->getAll();	

//print_r($row);

echo json_encode($row);


?>