<?php
$no_kartu		= strtoupper($_GET["term"]);

$db 			= getDB("storage");
	
$query 			= "SELECT KARTU_STRIPPING.*,
                            MASTER_CONTAINER.SIZE_, 'STRIPPING' KEGIATAN, YARD_AREA.NAMA_YARD LOKASI, BLOCKING_AREA.NAME BLOK_, PLACEMENT.ROW_, PLACEMENT.SLOT_, PLACEMENT.TIER_
                   FROM MASTER_CONTAINER 
                   INNER JOIN KARTU_STRIPPING ON MASTER_CONTAINER.NO_CONTAINER = KARTU_STRIPPING.NO_CONTAINER
                   INNER JOIN REQUEST_STRIPPING ON KARTU_STRIPPING.NO_REQUEST = REQUEST_STRIPPING.NO_REQUEST
                   left JOIN PLACEMENT ON MASTER_CONTAINER.NO_CONTAINER = PLACEMENT.NO_CONTAINER AND REQUEST_STRIPPING.NO_REQUEST_RECEIVING = PLACEMENT.NO_REQUEST_RECEIVING
                   left JOIN BLOCKING_AREA ON PLACEMENT.ID_BLOCKING_AREA = BLOCKING_AREA.ID
                   left JOIN YARD_AREA ON BLOCKING_AREA.ID_YARD_AREA = YARD_AREA.ID
                   WHERE KARTU_STRIPPING.NO_KARTU LIKE '%$no_kartu%' 
                   AND KARTU_STRIPPING.AKTIF = 'Y' --AND SYSDATE-1 <= KARTU_STRIPPING.TGL_BERLAKU AND ROWNUM <= 5                   
                   UNION                   
                   SELECT KARTU_STUFFING.*,
                            MASTER_CONTAINER.SIZE_, 'STUFFING' KEGIATAN, YARD_AREA.NAMA_YARD LOKASI, BLOCKING_AREA.NAME BLOK_, PLACEMENT.ROW_, PLACEMENT.SLOT_, PLACEMENT.TIER_
                   FROM MASTER_CONTAINER 
                   INNER JOIN KARTU_STUFFING ON MASTER_CONTAINER.NO_CONTAINER = KARTU_STUFFING.NO_CONTAINER
                   INNER JOIN REQUEST_STUFFING ON KARTU_STUFFING.NO_REQUEST = REQUEST_STUFFING.NO_REQUEST
                   INNER JOIN PLACEMENT ON MASTER_CONTAINER.NO_CONTAINER = PLACEMENT.NO_CONTAINER AND REQUEST_STUFFING.NO_REQUEST_RECEIVING = PLACEMENT.NO_REQUEST_RECEIVING
                   INNER JOIN BLOCKING_AREA ON PLACEMENT.ID_BLOCKING_AREA = BLOCKING_AREA.ID
                   INNER JOIN YARD_AREA ON BLOCKING_AREA.ID_YARD_AREA = YARD_AREA.ID
                   WHERE KARTU_STUFFING.NO_KARTU LIKE '%$no_kartu%' 
                   AND KARTU_STUFFING.AKTIF = 'Y' AND SYSDATE-1 <= KARTU_STUFFING.TGL_BERLAKU AND ROWNUM <= 5
				   ";
				   
//$query = "SELECT NO_REQUEST,NO_CONTAINER FROM CONTAINER_STRIPPING WHERE NO_REQUEST LIKE '%$no_kartu%' AND CONTAINER_STRIPPING.AKTIF='Y'";
//echo $query;
//$query			= "";				   
$result			= $db->query($query);
$row			= $result->getAll();	

//print_r($row);

echo json_encode($row);


?>